import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Slider from '../components/slider'
import WhyChooseUs from '../components/whychooseus'
import PopularTrips from '../components/populartrips'
import Destination from '../components/destination'
import Form from '../components/form'
import { useState } from 'react'
import Populartours from '../components/populartours'
import { BiSupport } from 'react-icons/bi'
import { AiFillCloseCircle, AiOutlineForm } from 'react-icons/ai'
import Header from '../components/header'
import Footer from '../components/footer'
import { motion } from 'framer-motion'
import { fetchStrapi } from '../lib/strapi'

type HeroSlide = {
  id: number;
  imageUrl: string;
  headline: string;
  subheadline: string;
};

type TourCard = {
  slug: string;
  title: string;
  rating: number | null;
  imageUrl: string;
  primaryDestination?: string | null;
};

type DestinationCard = {
  slug: string;
  name: string;
  shortDescription?: string;
  imageUrl: string;
};

export default function Home({
  heroSlides,
  tours,
  destinations,
}: {
  heroSlides: HeroSlide[];
  tours: TourCard[];
  destinations: DestinationCard[];
}) {
  const [showForm, setshowForm] = useState(false);
  return (
    <div>
      <Head>
        <title>Zeelan Tours - One Island, Different Experience </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/asset/image/logo-port.png" />
      </Head>

      <main className="pt-24 lg:pt-28">

        <motion.div
          className='fixed top-0 left-0 right-0 z-50 bg-gradient-to-r from-blue-100 via-white to-pink-100 shadow-md'
          initial={{ y: -40, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ duration: 0.6, ease: 'easeOut' }}
        >
          <Header />
        </motion.div>
        <div className='grid grid-cols-1 h-[40rem]'>
          <div className=' relative z-20 h-[40rem]'>
            <Slider slides={heroSlides} />
          </div>
          {(showForm) ?
            <div className=' max-md:hidden flex fixed z-50 top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2'><Form /><button className='flex' onClick={() => setshowForm(!showForm)}><AiFillCloseCircle className=' text-2xl' /></button></div> : <></>}
        </div>

        <motion.div
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, amount: 0.2 }}
          transition={{ duration: 0.6, ease: 'easeOut' }}
        >
          <Populartours tours={tours} />
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, amount: 0.2 }}
          transition={{ duration: 0.6, ease: 'easeOut', delay: 0.1 }}
        >
          <WhyChooseUs />
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, amount: 0.2 }}
          transition={{ duration: 0.6, ease: 'easeOut', delay: 0.1 }}
        >
          <PopularTrips destinations={destinations.slice(0, 4)} />
        </motion.div>

        {/* <motion.div
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, amount: 0.2 }}
          transition={{ duration: 0.6, ease: 'easeOut', delay: 0.1 }}
        >
          <Destination destinations={destinations} />
        </motion.div> */}
      </main>

      <Footer />
    </div>
  )
}

export async function getStaticProps() {
  const strapiUrl = process.env.STRAPI_URL || 'http://localhost:1337';

  const [homepageRes, toursRes, destinationsRes] = await Promise.all([
    fetchStrapi('/api/hompage?populate[heroslide][populate]=image'),
    fetchStrapi('/api/tours?filters[isFeatured][$eq]=true&populate=*'),
    fetchStrapi('/api/destinations?populate=*'),
  ]);

  const heroSlides: HeroSlide[] =
    homepageRes?.data?.heroslide?.map((slide: any) => {
      const img = slide?.image;
      return {
        id: slide?.id ?? Math.floor(Math.random() * 1e9),
        imageUrl: img?.url ? `${strapiUrl}${img.url}` : '/asset/image/slide1.webp',
        headline: slide?.headline ?? '',
        subheadline: slide?.subheadline ?? '',
      };
    }) ?? [];

  const tours: TourCard[] =
    toursRes?.data?.map((item: any) => {
      const firstDest = item?.destinations?.[0]?.name ?? null;
      return {
        slug: item?.slug ?? null,
        title: item?.title ?? '',
        rating: item?.rating ?? null,
        imageUrl: item?.imageURL || '/asset/image/taj.webp',
        primaryDestination: firstDest,
      };
    }) ?? [];

  const destinations: DestinationCard[] =
    destinationsRes?.data?.map((item: any) => {
      return {
        slug: item?.slug ?? null,
        name: item?.name ?? '',
        shortDescription: item?.shortDescription ?? '',
        imageUrl: item?.imageURL || '/asset/image/kolkata.webp',
      };
    }) ?? [];

  return {
    props: { heroSlides, tours, destinations },
    revalidate: 60,
  };
}
